---

# DEPRECATED(JEFF): This syntax is deprecated and 
# shall be removed in a later version of docker-compose.  
#version: 3

networks:
  proxy:
    attachable: true
    driver: overlay
    external: true

volumes:
    portainer-data:
      external: true

services:

  whoami:
    container_name: whoami-1
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    env_file:
      .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
    ports:
      - 3000:80/tcp

  portainer:
    restart: unless-stopped
    container_name: portainer-1
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

  #pytorch:
    #restart: unless-stopped
    #container_name: pytorch-1
    #build:
      #context: "."
      #dockerfile: "Dockerfile_pytorch"
    #image:
    #env_file:
    #- .env.dev
