services:

    container_name: whoami-1
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    env_file:
      .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
    ports:
      - 3000:80/tcp
