---

# DEPRECATED(JEFF): This syntax is deprecated and 
# shall be removed in a later version of docker-compose.  
#version: 3

networks:
  proxy:
    attachable: true
    driver: overlay
    external: true

volumes:
    portainer-data:
      external: true

services:

  #whoami:
    #extends:
      #file: compose_null.yml
      #service: whoami1

  #portainer:
    #extends:
      #file: compose_portainer.yml
      #file: compose_null.yml
      #service: portainer-ce

  nvidia-toolkit:
    extends:
      file: compose_nv.yml
      service: nvidia-container-toolkit

  pytorch-test:
    extends:
      file: compose_pytorch.yml
      service: pytorch
